name: Django Deploy Runner
on: 
  workflow_dispatch:
    
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Project
      uses: actions/checkout@v2
    - name: Transfer Files to the Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "/home/runner/work/ASCII-Generator.site/ASCII-Generator.site"
        target: "/home/user/ascii-generator/ASCII-Generator.site/"
        strip_components: 2
    - name: Deploy on the Server
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/user/ascii-generator/
          docker-compose up -d web_backup
          sleep 15
          docker-compose up -d --build db nginx memcached web img_cleaner
          sleep 15
          docker stop web_app_backup
          docker rm web_app_backup
          docker image prune -a -f
